"""
Execution-based Self-Consistency: Pseudo-labeling for Self-Judgment when no gold_sql exists.


This module generates N diverse SQL candidates for the SAME question, executes
all of them on the target database, and uses AGREEMENT between candidates
(execution-result voting) as a proxy signal instead of gold comparison:

  - pseudo_execution_match : did the primary SQL execute without error?
  - pseudo_exact_match     : did the primary SQL's result set match the
                              majority-vote result set among all candidates?
  - agreement_ratio        : majority_cluster_size / n_candidates
                              (used later to DISCOUNT confidence in
                              SelfJudgment, since this is not ground truth)

This is the standard "self-consistency" approach used when no ground truth
is available (see ReasoningBank paper, and general self-consistency /
majority-voting literature for LLM reasoning).

IMPORTANT LIMITATION (must be stated in thesis Limitations section):
If the LLM makes the SAME mistake across multiple candidates (a systematic/
correlated error), self-consistency will confidently vote for the WRONG
answer. This proxy is strictly weaker than real gold-based evaluation and
should never be presented as equivalent to it.
"""

import asyncio
import time
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional

from utils.logging_utils import get_logger

logger = get_logger(__name__)

# Reuse the SAME execution + result-comparison primitives already used for
# Spider/WikiSQL execution accuracy, so pseudo-labels are computed with the
# exact same semantics as the benchmark's own EX metric.
from src.evaluation.exec_evaluator import exec_on_db, result_eq, postprocess


@dataclass
class ConsistencyCandidate:
    """One SQL candidate generated for self-consistency voting."""
    sql: str
    temperature: float
    executed_ok: bool = False
    denotation: Optional[object] = None   # execution result, used for clustering
    cluster_id: Optional[int] = None
    generation_time: float = 0.0
    error: Optional[str] = None


@dataclass
class SelfConsistencyResult:
    """Everything SelfJudgment / reasoning_pipeline needs, no gold required."""
    primary_sql: str
    pseudo_execution_match: bool
    pseudo_exact_match: float          # 0.0 or 1.0 (kept as float to match Trajectory.exact_match type)
    agreement_ratio: float             # majority_size / n_candidates, in [0, 1]
    majority_cluster_size: int
    n_candidates: int
    label_source: str = "self_consistency"
    candidates: List[ConsistencyCandidate] = field(default_factory=list)


class ExecutionSelfConsistency:
    """
    Generates diverse candidates for a question and votes on execution results
    to produce a pseudo ground-truth signal for Self-Judgment.

    Does NOT know how to build prompts itself — the caller (reasoning_pipeline)
    passes in a `candidate_generator_fn(temperature) -> sql_string` closure that
    already has the question/schema/strategies baked in. This keeps this module
    decoupled from prompt-construction logic.
    """

    def __init__(
        self,
        agreement_threshold: float = 0.6,
        max_confidence: float = 0.85,
    ):
        """
        Args:
            agreement_threshold: minimum agreement_ratio required for the
                primary candidate to be labeled pseudo_exact_match=1.0.
                Below this, we don't trust the majority enough to call it
                "correct" — trajectory becomes EXECUTION_FAILURE instead.
            max_confidence: hard cap on confidence for ANY self-consistency
                judgment. Even 100% agreement across candidates is still not
                gold-verified truth, so SelfJudgment should never reach the
                same 1.0 confidence it gets from real gold comparison.
        """
        self.agreement_threshold = agreement_threshold
        self.max_confidence = max_confidence
        logger.info(
            f"ExecutionSelfConsistency initialized "
            f"(agreement_threshold={agreement_threshold}, max_confidence={max_confidence})"
        )

    def generate_pseudo_labels(
        self,
        primary_sql: str,
        db_path: str,
        candidate_generator_fn: Callable[[float], str],
        n_additional_candidates: int = 4,
        temperatures: Optional[List[float]] = None,
    ) -> SelfConsistencyResult:
        """
        Args:
            primary_sql: the SQL already generated by the normal pipeline
                (this is the one whose pseudo-label we actually need).
            db_path: path to the target .sqlite database for execution.
            candidate_generator_fn: callable(temperature: float) -> sql string.
                Caller is responsible for prompt construction; this should
                reuse the SAME question/schema/strategies as primary_sql,
                just resampled at a different temperature.
            n_additional_candidates: how many EXTRA candidates to generate
                besides primary_sql (total candidates = n_additional + 1).
            temperatures: explicit temperature list for extra candidates.
                Defaults to a spread between 0.3 and 0.9.

        Returns:
            SelfConsistencyResult with pseudo_exact_match / pseudo_execution_match
            / agreement_ratio ready to feed into process_evaluation_result().
        """
        if temperatures is None:
            if n_additional_candidates <= 1:
                temperatures = [0.6]
            else:
                lo, hi = 0.3, 0.9
                step = (hi - lo) / (n_additional_candidates - 1)
                temperatures = [round(lo + i * step, 2) for i in range(n_additional_candidates)]

        candidates: List[ConsistencyCandidate] = [
            ConsistencyCandidate(sql=primary_sql, temperature=0.0)  # primary = greedy/original
        ]

        # ── Generate extra candidates ────────────────────────────────────────
        for temp in temperatures:
            start = time.time()
            try:
                sql = candidate_generator_fn(temp)
                candidates.append(ConsistencyCandidate(
                    sql=sql or "SELECT 1",
                    temperature=temp,
                    generation_time=time.time() - start,
                ))
            except Exception as e:
                logger.debug(f"Self-consistency candidate generation failed at temp={temp}: {e}")
                candidates.append(ConsistencyCandidate(
                    sql="SELECT 1",
                    temperature=temp,
                    generation_time=time.time() - start,
                    error=str(e),
                ))

        # ── Execute every candidate on the real database ─────────────────────
        for cand in candidates:
            try:
                flag, denotation = asyncio.run(exec_on_db(db_path, postprocess(cand.sql)))
                cand.executed_ok = (flag != "exception")
                cand.denotation = denotation if cand.executed_ok else None
            except Exception as e:
                cand.executed_ok = False
                cand.error = cand.error or str(e)

        # ── Cluster candidates by execution-result equality ──────────────────
        # Two candidates are "in the same cluster" if their result sets match
        # via the same result_eq() used by the official execution-accuracy metric.
        clusters: List[List[int]] = []
        for i, cand in enumerate(candidates):
            if not cand.executed_ok:
                continue
            placed = False
            for cluster in clusters:
                rep = candidates[cluster[0]]
                try:
                    if result_eq(rep.denotation, cand.denotation, order_matters=False):
                        cluster.append(i)
                        placed = True
                        break
                except Exception:
                    continue
            if not placed:
                clusters.append([i])

        for cluster_id, cluster in enumerate(clusters):
            for idx in cluster:
                candidates[idx].cluster_id = cluster_id

        executed_count = sum(1 for c in candidates if c.executed_ok)
        primary = candidates[0]

        if not clusters or executed_count == 0:
            # Nothing executed at all — can't vote on anything.
            result = SelfConsistencyResult(
                primary_sql=primary_sql,
                pseudo_execution_match=False,
                pseudo_exact_match=0.0,
                agreement_ratio=0.0,
                majority_cluster_size=0,
                n_candidates=len(candidates),
                candidates=candidates,
            )
            logger.debug(f"Self-consistency: no candidates executed successfully for {primary_sql!r}")
            return result

        majority_cluster = max(clusters, key=len)
        majority_size = len(majority_cluster)
        agreement_ratio = majority_size / len(candidates)

        primary_in_majority = primary.cluster_id is not None and primary.cluster_id == candidates[majority_cluster[0]].cluster_id

        pseudo_exact_match = 1.0 if (
            primary.executed_ok
            and primary_in_majority
            and agreement_ratio >= self.agreement_threshold
        ) else 0.0

        result = SelfConsistencyResult(
            primary_sql=primary_sql,
            pseudo_execution_match=primary.executed_ok,
            pseudo_exact_match=pseudo_exact_match,
            agreement_ratio=agreement_ratio,
            majority_cluster_size=majority_size,
            n_candidates=len(candidates),
            candidates=candidates,
        )

        logger.debug(
            f"Self-consistency: {majority_size}/{len(candidates)} agree "
            f"(ratio={agreement_ratio:.2f}) -> pseudo_exact_match={pseudo_exact_match}"
        )
        return result